### PR TITLE
Renamed LVMM model to ArmadilloV1 and added autoregressive models

### PR DESCRIPTION
**Pull request by sxsheng**
Cleaned up some of the directories and renamed LVMM to ArmadilloV1. You should now import forecasters as follows

`from forecasters import ArmadilloV1, AR`

The AR model only forecasts based on the most recent time steps available and returns the indicated number of time steps, `n`, it wants to forecast into the future.

Next PR will have the updated `ArmadilloV2`.

### CODE REVIEW

**Review by ZeratuuLL — CHANGES_REQUESTED** [review]
I think we need to have a meeting so that I can fully understand your code. Here is a list of my questions:

1. Why did you add a _ before the file names? I remember that this means pseudo-private in Python. 
2. In `_model.py`, I need to understand what is Scaling correction for AR model and how we are going to use it...
3. In `_model.py`, class ARLCI 's `train_step` method name seems to be inconsistent
4. For `test_autoregressive.py`, let's make it a class. I can do this later if you want. This is not urgent. As for the content, I need to have a better understanding about AR model first, see question 2.
5. For `setup.py`, I am not sure if we need to specify versions? I am not sure what will happen if someone tries to install our module if tensorflow 1.X version is installed.

**Comment by sxsheng** [comment]
Sure lets have a meeting, maybe after today's group meeting? I'll try to answer some of your questions  here.

1. I put _ before the file names because they shouldn't be accessed by the person using the API. All they need to be able to do is just import the models by doing `from forecasters import AR, ARLIC`. I might also change the __init__ file so that it's something like `from forecasters.autoregressive import AR, ARLIC` for more specificity. 
2. The scaling correction was originally there because it was one way to fit leading indicators to case counts. I'm not really sure we need that method or whether we'll even use the simple AR model for production. It was meant to be a strawman forecaster. We can remove it if necessary. The ARLIC model is the important one for now.
3. Yeah, ARLIC model was supposed to use the Keras API. That's why that `train_step` method is there. Did you mean it's inconsistent with the one from the AR model above? Keras already has a fit method and I didn't want to overwrite that yet. I do plan to to unify the interface however. I can do that later today. 
4. The AR model isn't going to be used in production. The ARLIC model is the one that we will be using and demoing.
5. It would simply overwrite the existing installation if a preexisting version already exists. I do think we should specify versions since it would help us avoid compatibility issues when other users start to use our package. For example Tensorflow in particular I might specify v2.3.1 since that's what I'm testing my code on.

**Comment by sxsheng** [comment]
4. What are you suggesting when you say you want to turn it into a class? For my tests I typically have it organized as methods and then just run pytest on the file. `pytest tests/test_autoregressive.py`

**Comment by ZeratuuLL** [comment]
> 1. What are you suggesting when you say you want to turn it into a class? For my tests I typically have it organized as methods and then just run pytest on the file. `pytest tests/test_autoregressive.py` Did you mean you want the individual methods I currently have in their organized into a class?

This file can work as an example~ 
https://github.com/hdt-modeling/hdt-forecast/blob/master/hdt_util/tests/test_get_covidcast.py

**Comment by ZeratuuLL** [comment]
Only a minor edit is needed. Put it in the next PR.

**Pull request merged**
